export interface Governorate {
  id: string;
  nameAr: string;
  nameEn: string;
  region: 'cairo_giza' | 'delta' | 'upper_egypt';
  regionNameAr: string;
  regionNameEn: string;
  rate: number;
}

export const MIN_ORDER_AMOUNT = 200;
export const FREE_SHIPPING_THRESHOLD = 500;

export const SHIPPING_RATES = {
  cairo_giza: 80,
  delta: 90,
  upper_egypt: 130,
} as const;

export const GOVERNORATES: Governorate[] = [
  // 1. القاهرة والجيزة — 80 ج.م
  {
    id: 'cairo',
    nameAr: 'القاهرة',
    nameEn: 'Cairo',
    region: 'cairo_giza',
    regionNameAr: 'القاهرة والجيزة',
    regionNameEn: 'Cairo & Giza',
    rate: 80,
  },
  {
    id: 'giza',
    nameAr: 'الجيزة',
    nameEn: 'Giza',
    region: 'cairo_giza',
    regionNameAr: 'القاهرة والجيزة',
    regionNameEn: 'Cairo & Giza',
    rate: 80,
  },

  // 2. الدلتا والإسكندرية ومدن القناة — 90 ج.م
  {
    id: 'alex',
    nameAr: 'الإسكندرية',
    nameEn: 'Alexandria',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'qalyubia',
    nameAr: 'القليوبية',
    nameEn: 'Qalyubia',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'dakahlia',
    nameAr: 'الدقهلية (المنصورة)',
    nameEn: 'Dakahlia (Mansoura)',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'gharbia',
    nameAr: 'الغربية (طنطا)',
    nameEn: 'Gharbia (Tanta)',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'sharqia',
    nameAr: 'الشرقية (الزقازيق)',
    nameEn: 'Sharqia (Zagazig)',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'monufia',
    nameAr: 'المنوفية (شبين الكوم)',
    nameEn: 'Monufia (Shibin El Kom)',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'beheira',
    nameAr: 'البحيرة (دمنهور)',
    nameEn: 'Beheira (Damanhur)',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'kafr_el_sheikh',
    nameAr: 'كفر الشيخ',
    nameEn: 'Kafr El Sheikh',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'damietta',
    nameAr: 'دمياط',
    nameEn: 'Damietta',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'port_said',
    nameAr: 'بورسعيد',
    nameEn: 'Port Said',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'ismailia',
    nameAr: 'الإسماعيلية',
    nameEn: 'Ismailia',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },
  {
    id: 'suez',
    nameAr: 'السويس',
    nameEn: 'Suez',
    region: 'delta',
    regionNameAr: 'الدلتا والقناة',
    regionNameEn: 'Delta & Canal',
    rate: 90,
  },

  // 3. الصعيد والغردقة والبحر الأحمر وسيناء — 130 ج.م
  {
    id: 'red_sea',
    nameAr: 'البحر الأحمر (الغردقة)',
    nameEn: 'Red Sea (Hurghada)',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'faiyum',
    nameAr: 'الفيوم',
    nameEn: 'Faiyum',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'beni_suef',
    nameAr: 'بني سويف',
    nameEn: 'Beni Suef',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'minya',
    nameAr: 'المنيا',
    nameEn: 'Minya',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'asyut',
    nameAr: 'أسيوط',
    nameEn: 'Asyut',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'sohag',
    nameAr: 'سوهاج',
    nameEn: 'Sohag',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'qena',
    nameAr: 'قنا',
    nameEn: 'Qena',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'luxor',
    nameAr: 'الأقصر',
    nameEn: 'Luxor',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'aswan',
    nameAr: 'أسوان',
    nameEn: 'Aswan',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'sinai',
    nameAr: 'جنوب سيناء (شرم الشيخ)',
    nameEn: 'South Sinai (Sharm El Sheikh)',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'north_sinai',
    nameAr: 'شمال سيناء',
    nameEn: 'North Sinai',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'matrouh',
    nameAr: 'مطروح والساحل الشمالي',
    nameEn: 'Matrouh & North Coast',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
  {
    id: 'new_valley',
    nameAr: 'الوادي الجديد',
    nameEn: 'New Valley',
    region: 'upper_egypt',
    regionNameAr: 'الصعيد والغردقة',
    regionNameEn: 'Upper Egypt & Hurghada',
    rate: 130,
  },
];

export const GOVERNORATES_DISTRICTS: Record<string, string[]> = {
  cairo: [
    'المعادي',
    'مدينة نصر',
    'مصر الجديدة',
    'التجمع الخامس (القاهرة الجديدة)',
    'التجمع الأول',
    'التجمع الثالث',
    'الشروق',
    'مدينتي',
    'الرحاب',
    'بدر',
    'المقطم',
    'شبرا',
    'حلوان',
    'عين شمس',
    'الزيتون',
    'الزمالك',
    'وسط البلد',
    'العباسية',
    'المنيل',
    'حدائق القبة',
    'المطرية',
    'الوايلي',
    'باب الشعرية',
    'البساتين',
    'دار السلام',
    '15 مايو',
  ],
  giza: [
    'الدقي',
    'المهندسين',
    'مدينة 6 أكتوبر',
    'الشيخ زايد',
    'الهرم',
    'فيصل',
    'العمرانية',
    'بولاق الدكرور',
    'إمبابة',
    'الوراق',
    'العجوزة',
    'حدائق الأهرام',
    'الحوامدية',
    'البدرشين',
    'أوسيم',
    'منشأة القناطر',
    'الصف',
    'أطفيح',
    'العياط',
  ],
  alex: [
    'سموحة',
    'سيدي جابر',
    'لوران',
    'ميامي',
    'محرم بك',
    'المنشية',
    'سيدي بشر',
    'العجمي',
    'الرمل',
    'المنتزه',
    'بحري والأنفوشي',
    'الإبراهيمية',
    'كليوباترا',
    'الشاطبي',
    'جناكليس',
    'المندرة',
    'العصافرة',
    'العامرية',
    'برج العرب',
    'كينج مريوط',
  ],
  qalyubia: [
    'بنها',
    'شبرا الخيمة',
    'قليوب',
    'الخانكة',
    'القناطر الخيرية',
    'طوخ',
    'كفر شكر',
    'العبور',
    'شبين القناطر',
    'الخصوص',
    'قها',
  ],
  dakahlia: [
    'المنصورة',
    'ميت غمر',
    'السنبلاوين',
    'دكرنس',
    'بلقاس',
    'شربين',
    'المنزلة',
    'طلخا',
    'أجا',
    'نبروه',
    'بني عبيد',
    'ميت سلسيل',
    'تمى الأمديد',
    'الجمالية',
    'المطرية',
  ],
  gharbia: [
    'طنطا',
    'المحلة الكبرى',
    'زفتى',
    'كفر الزيات',
    'سمنود',
    'السنطة',
    'بسيون',
    'قطور',
  ],
  sharqia: [
    'الزقازيق',
    'العاشر من رمضان',
    'بلبيس',
    'منيا القمح',
    'فاقوس',
    'أبو حماد',
    'ديرب نجم',
    'الحسينية',
    'ههيا',
    'كفر صقر',
    'أبو كبير',
    'الصالحية الجديدة',
    'مشتول السوق',
    'الإبراهيمية',
  ],
  monufia: [
    'شبين الكوم',
    'قويسنا',
    'بركة السبع',
    'منوف',
    'أشمون',
    'تلا',
    'الشهداء',
    'مدينة السادات',
    'الباجور',
    'سرس الليان',
  ],
  beheira: [
    'دمنهور',
    'كفر الدوار',
    'إيتاي البارود',
    'كوم حمادة',
    'أبو حمص',
    'حوش عيسى',
    'رشيد',
    'الدلنجات',
    'إدكو',
    'وادي النطرون',
    'شبراخيت',
    'المحمودية',
    'بدر',
    'النوبارية الجديدة',
  ],
  kafr_el_sheikh: [
    'كفر الشيخ',
    'دسوق',
    'فوه',
    'مطوبس',
    'سيدي سالم',
    'بيلا',
    'قلين',
    'الرياض',
    'الحامول',
    'بلطيم',
    'برج البرلس',
  ],
  damietta: [
    'مدينة دمياط',
    'دمياط الجديدة',
    'رأس البر',
    'كفر سعد',
    'فارسكور',
    'الزرقا',
    'الروضة',
    'ميت أبو غالب',
    'عزبة البرج',
    'كفر البطيخ',
  ],
  port_said: [
    'حي الشرق',
    'حي العرب',
    'حي الضواحي',
    'حي الزهور',
    'حي المناخ',
    'حي الجنوب',
    'مدينة بورفؤاد',
    'حي الغرب',
  ],
  ismailia: [
    'مدينة الإسماعيلية',
    'فايد',
    'القنطرة غرب',
    'القنطرة شرق',
    'التل الكبير',
    'أبو صوير',
    'القصاصين',
  ],
  suez: [
    'حي السويس',
    'حي الأربعين',
    'حي عتاقة',
    'حي فيصل',
    'حي الجناين',
    'العين السخنة',
  ],
  red_sea: [
    'الغردقة',
    'الجونة',
    'سفاجا',
    'القصير',
    'مرسى علم',
    'رأس غارب',
    'حلايب وشلاتين',
  ],
  faiyum: [
    'مدينة الفيوم',
    'سنورس',
    'إطسا',
    'طامية',
    'يوسف الصديق',
    'أبشواي',
    'الفيوم الجديدة',
  ],
  beni_suef: [
    'مدينة بني سويف',
    'الواسطى',
    'ناصر',
    'إهناسيا',
    'ببا',
    'الفشن',
    'سمسطا',
    'بني سويف الجديدة',
  ],
  minya: [
    'مدينة المنيا',
    'مغاغة',
    'بني مزار',
    'مطاي',
    'سمالوط',
    'أبو قرقاص',
    'ملوي',
    'دير مواس',
    'العدوة',
    'المنيا الجديدة',
  ],
  asyut: [
    'مدينة أسيوط',
    'ديروط',
    'القوصية',
    'أبنوب',
    'منفلوط',
    'الفتح',
    'أبو تيج',
    'الغنايم',
    'ساحل سليم',
    'البداري',
    'صدفا',
    'أسيوط الجديدة',
  ],
  sohag: [
    'مدينة سوهاج',
    'أخميم',
    'طهطا',
    'جرجا',
    'المراغة',
    'المنشأة',
    'البلينا',
    'جهينة',
    'ساقلتة',
    'دار السلام',
    'طما',
    'سوهاج الجديدة',
  ],
  qena: [
    'مدينة قنا',
    'نجع حمادي',
    'دشنا',
    'قوص',
    'أبو تشت',
    'الوقف',
    'قفط',
    'نقادة',
    'فرشوط',
    'قنا الجديدة',
  ],
  luxor: [
    'مدينة الأقصر',
    'إسنا',
    'أرمنت',
    'الطود',
    'البياضية',
    'القرنة',
    'الزينية',
    'طيبة الجديدة',
  ],
  aswan: [
    'مدينة أسوان',
    'دراو',
    'كوم أمبو',
    'نصر النوبة',
    'إدفو',
    'أسوان الجديدة',
    'أبو سمبل',
  ],
  sinai: [
    'شرم الشيخ',
    'دهب',
    'نويبع',
    'طابا',
    'طور سيناء',
    'رأس سدر',
    'سانت كاترين',
    'أبو رديس',
    'أبو زنيمة',
  ],
  north_sinai: [
    'العريش',
    'الشيخ زويد',
    'رفح',
    'بئر العبد',
    'الحسنة',
    'نخل',
  ],
  matrouh: [
    'مرسى مطروح',
    'العلمين',
    'مارينا والساحل الشمالي',
    'الحمام',
    'الضبعة',
    'سيوة',
    'السلوم',
    'النجيلة',
  ],
  new_valley: [
    'الخارجة',
    'الداخلة',
    'الفرافرة',
    'باريس',
    'بلاط',
  ],
};

export function getShippingRate(govId: string): number {
  const gov = GOVERNORATES.find((g) => g.id === govId);
  return gov ? gov.rate : 80;
}

export function getGovernorate(govId: string): Governorate | undefined {
  return GOVERNORATES.find((g) => g.id === govId);
}

export function getDistricts(govId: string): string[] {
  return GOVERNORATES_DISTRICTS[govId] || ['المركز الرئيسي'];
}
